export const APP_NAME = 'PssPpr'
export const APP_SHORT_NAME = 'PP'
export const APP_VERSION = 'v.1.0.4'

export const NAV_BUTTON_APP = '+ App'
export const NAV_BUTTON_TOOL = '+ Tool'
export const NAV_BUTTON_NEW = 'New'

export const HOME_TOOLS = 'Tools'
export const HOME_APPS = 'Apps'
export const HOME_EMPTY_DATA = '- Empty data -'
export const HOME_DISABLED_ALL_SECTION = '- Disabled all sections -'
export const HOME_TOOL_NOTE = 'If the tool name is repeated, they are grouped.'
export const HOME_ORDER_DATA = 'Order data by code + name (Apps) and name + subName (Tools)'
export const HOME_ATENTION_TITLE = 'ATENTION'
export const HOME_ATENTION_DESCRIPTION = ': For fields \'Ref. Password\' NO add real data exact, only referencies. The referencies anoted in paper with your respective asociation of password real (or part). applicable also for \'Ref. User\''
export const BUTTON_TEXT_SAVE = 'Save'
export const BUTTON_TEXT_DELETE = 'Delete'
export const BUTTON_TEXT_OPEN = 'Open'
export const HOME_README_TITLE = 'README'
export const HOME_README_NOTE = 'NOTE'
export const HOME_README_YOUR = '- Your information, your responsibility. -'
export const HOME_README_USE = 'Application used for personal use, the information is stored on the device where it is used.'
export const HOME_README_YOUR_OPTION = 'Or use your option, but never store it all on your mobile, desktop, etc.'
export const HOME_README_PPR_EXAMPLE = 'Paper Example Option'
export const HOME_README_REAL_PASS = 'Real Password'
export const HOME_README_WHERE_ASTERISK = '(*) Where is each asterisk, stored in your head.'
export const HOME_README_EXAMPLE_REF01 = 'GML1'
export const HOME_README_EXAMPLE_PSS1A = '$123WW_$%x'
export const HOME_README_EXAMPLE_PSS1B = 'qwerty12$03'
export const HOME_README_EXAMPLE_REF02 = 'SKP0'
export const HOME_README_EXAMPLE_PSS2A = '$***WW_$%x'
export const HOME_README_EXAMPLE_PSS2B = 'qwerty**$0*'

export const LIST_APP_EDIT = 'Edit'
export const LIST_APP_ADD_ENV = 'Add env'

export const ALERT_CONFIRM_TITLE = 'Are you sure?'
export const ALERT_CONFIRM_TEXT = 'You won\'t be able to revert this!'
export const ALERT_CONFIRM_BUTTON_TEXT = 'Yes, delete it!'

export const ACTION_NEW = 'new'
export const ACTION_SAVE = 'save'
export const ACTION_DELETE = 'delete'
export const ACTION_GET = 'get'
export const ACTION_LIST = 'list'
export const ACTION_EDIT = 'edit'
export const ACTION_MSG_NEW = 'successfully added.'
export const ACTION_MSG_DELETE = 'successfully deleted.'
export const ACTION_MSG_EDIT = 'successfully updated.'
export const ACTION_MSG_EDIT_ERR = 'nothing was updated.'
export const ACTION_FAILED = 'Failed to '

export const OBJ_APP = 'App'
export const OBJ_ENV = 'Env'
export const OBJ_TOOL= 'Tool'
export const OBJ_SETTING = 'Setting'

export const FORM_TOOL_TITLE_NEW = 'New Tool'
export const FORM_TOOL_TITLE_EDIT = 'Tool #'
export const FORM_ENV_TITLE_NEW = 'New Env'
export const FORM_ENV_TITLE_EDIT = 'Env #'
export const FORM_APP_TITLE_NEW = 'New App'
export const FORM_APP_TITLE_EDIT = 'App #'

export const FORM_BUTTON_TYPE_SAVE = 'save'
export const FORM_BUTTON_TYPE_DELETE = 'delete'

export const FORM_APP_NAME_LABEL = 'Name'
export const FORM_APP_NAME_PLACEHOLDER = 'Name app..'
export const FORM_APP_CODE_LABEL = 'Code'
export const FORM_APP_CODE_PLACEHOLDER = 'Code..'
export const FORM_APP_GITHUB_LABEL = 'Github Link'
export const FORM_APP_GITHUB_PLACEHOLDER = 'https://github.com'
export const FORM_APP_DOC_LINK_LABEL = 'Doc. Link'
export const FORM_APP_DOC_LINK_PLACEHOLDER = 'https://doc..'
export const FORM_APP_COMMENTS_LABEL = 'Comments'
export const FORM_APP_COMMENTS_PLACEHOLDER = 'Comments..'

export const FORM_ENV_NAME_LABEL = 'Name'
export const FORM_ENV_NAME_PLACEHOLDER = 'Name env..'
export const FORM_ENV_URL_LABEL = 'Url'
export const FORM_ENV_URL_PLACEHOLDER = 'Url env..'
export const FORM_ENV_IP_LABEL = 'Ip'
export const FORM_ENV_IP_PLACEHOLDER = '192.168..'
export const FORM_ENV_REF_USER_LABEL = 'Ref. User'
export const FORM_ENV_REF_USER_PLACEHOLDER = 'Ref. user..'
export const FORM_ENV_REF_PASS_LABEL = 'Ref. Password'
export const FORM_ENV_REF_PASS_PLACEHOLDER = 'Ref. password..'
export const FORM_ENV_COMMENTS_LABEL = 'Comments'
export const FORM_ENV_COMMENTS_PLACEHOLDER = 'Comments..'
export const FORM_ENV_EMPTY_ENVS = 'Empty name'

export const FORM_TOOL_NAME_LABEL = 'Name'
export const FORM_TOOL_NAME_PLACEHOLDER = 'Name Tool..'
export const FORM_TOOL_SUBNAME_LABEL = 'SubName'
export const FORM_TOOL_SUBNAME_PLACEHOLDER = 'SubName..'
export const FORM_TOOL_WEB_OFICIAL_LABEL = 'Web Oficial'
export const FORM_TOOL_WEB_OFICIAL_PLACEHOLDER = 'https://web-oficial..'
export const FORM_TOOL_ACCESS_URL_LABEL = 'Access URL'
export const FORM_TOOL_ACCESS_URL_PLACEHOLDER = 'https://access-url..'
export const FORM_TOOL_DOC_LINK_LABEL = 'Doc. Link'
export const FORM_TOOL_DOC_LINK_PLACEHOLDER = 'https://doc-link..'
export const FORM_TOOL_REF_USER_LABEL = 'Ref. User'
export const FORM_TOOL_REF_USER_PLACEHOLDER = 'Ref. user..'
export const FORM_TOOL_REF_PASS_LABEL = 'Ref. Password'
export const FORM_TOOL_REF_PASS_PLACEHOLDER = 'Ref. password..'
export const FORM_TOOL_COMMENTS_LABEL = 'Comments'
export const FORM_TOOL_COMMENTS_PLACEHOLDER = 'Comments..'

export const PENDING_DEVELOPMENT = 'Errr... ¡Pending development!'
export const LIST_ADD_TOOL = 'Add Tool'